.. ###############################################
.. Links
.. ###############################################

.. #### Documentation links
.. _Sphinx: http://www.sphinx-doc.org/en/master/
.. _reStructuredText: https://www.sphinx-doc.org/es/master/usage/restructuredtext/index.html
.. _`documentation details concerning ReST`: https://www.sphinx-doc.org/en/master/contents.html
.. _`Matplotlib documentation configuration`: https://matplotlib.org/devel/documenting_mpl.html
.. _API: https://en.wikipedia.org/wiki/Application_programming_interface
.. _Python: http://www.python.org/
.. _`PyPI files page`: https://pypi.org/
.. _`Python pip`: https://pip.pypa.io/en/stable/
.. _`pip installing instructions`: https://packaging.python.org/tutorials/installing-packages
.. _git: https://git-scm.com/
.. _`python environment`: https://docs.python.org/3/tutorial/venv.html
.. _Conda: https://docs.conda.io/en/latest/ 
.. _article: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04128-1
.. _miRBase: https://www.mirbase.org/
.. _`variant nomenclature`: https://academic.oup.com/bioinformatics/article/36/3/698/5556118

.. #### XICRA additional software links
.. _XICRA.stats: https://github.com/HCGB-IGTP/XICRA.stats
.. _Miraligner: https://seqcluster.readthedocs.io/mirna_annotation.html
.. _Optimir: https://rnajournal.cshlp.org/content/early/2019/02/28/rna.069708.118
.. _sRNAbench: https://bioinfo2.ugr.es/ceUGR/srnabench/
.. _miRTop: https://github.com/miRTop/mirtop 

.. #### Sites
.. _IGTP: http://www.germanstrias.org/
.. _HCGB: http://www.germanstrias.org/technology-services/genomica-bioinformatica/
.. _`XICRA github`: https://github.com/HCGB-IGTP/XICRA
.. _`report issues`: https://github.com/HCGB-IGTP/XICRA/issues
.. _`forking the project`: https://help.github.com/en/github/getting-started-with-github/fork-a-repo
.. _`creating pull requests`: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
.. _`Illumina sequencing`: https://support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
.. _Cutadapt: https://cutadapt.readthedocs.io/en/stable/