.. ###############################################
.. Links
.. ###############################################

.. #### Documentation links
.. _Sphinx: http://www.sphinx-doc.org/en/master/
.. _reStructuredText: https://www.sphinx-doc.org/es/master/usage/restructuredtext/index.html
.. _`documentation details concerning ReST`: https://www.sphinx-doc.org/en/master/contents.html
.. _`Matplotlib documentation configuration`: https://matplotlib.org/devel/documenting_mpl.html
.. _API: https://en.wikipedia.org/wiki/Application_programming_interface
.. _Python: http://www.python.org/
.. _`PyPI files page`: https://pypi.org/
.. _`Python pip`: https://pip.pypa.io/en/stable/
.. _`pip installing instructions`: https://packaging.python.org/tutorials/installing-packages
.. _git: https://git-scm.com/
.. _`python environment`: https://docs.python.org/3/tutorial/venv.html
.. _Conda: https://docs.conda.io/en/latest/ 

.. #### XICRA additional software links
.. _XICRA.stats: https://github.com/HCGB-IGTP/XICRA.stats

.. #### Sites
.. _IGTP: http://www.germanstrias.org/
.. _HCGB: http://www.germanstrias.org/technology-services/genomica-bioinformatica/
.. _`XICRA github`: https://github.com/HCGB-IGTP/XICRA